title: Your Big Cousin
future: true
author: Big Cousin
  name: Big Cousin
  email: 2856411911@qq.com
duoshuo: 
beian: 
cnzz: 
weibo:
github:
pygments: true
paginate: 20
truncate: true
about: "Big Cousin"
markdown: kramdown
highlighter: rouge
